### ISSUE TITLE
Feature request: Desktop version

### ISSUE THREAD

**Issue by michaelpearce-at** [fwouts/prmonitor#1030]
It would be awesome to have this in the global menu bar in macOS, or the Taskbar in Windows. That way I can switch browsers at ease without needing to make sure this extension is compatible.

I'm fairly sure I remember you mentioning you were playing around with this ;)

**Comment by fwouts** [comment]
Hey @michaelpearce-at 🙂 You're right, I did play around with this, but I never released it because of all the trouble related to signing desktop apps and paying fees to Apple and Microsoft.

As an alternative, I've been thinking about building it as a website which requests push notification permissions when you set it up (so it will work even if you close the website, and will open the website back if you click on the push notification). It would be a bit simpler to maintain from my end (no need to deal with OS quirks or to manage releases).

What do you think of this approach?

**Comment by michaelpearce-at** [comment]
Yeah, that could work. Though, it is nice to have the icon with the badged number of PRs visible all the time.

**Comment by fwouts** [comment]
Would a pinned tab work with your workflow, assuming the favicon updates dynamically?

**Comment by michaelpearce-at** [comment]
Yeah, that would be fine. I have some pinned tabs up all the time anyway, what's one more? 😁

**Comment by fwouts** [comment]
Hey Michael 👋 Just letting you know that I'm not forgetting about you, I'm exploring technical options at the moment.

**Comment by fwouts** [comment]
Hey @michaelpearce-at, check out https://prmonitor.zenc.io.

It's basically a forked version of the browser extension meant to run in a tab, using the JavaScript Notification API.

I'm not quite sure that it's good enough though. I suspect the tab will end up frozen in the background after a while so you won't necessarily get notifications reliably. There's now a Push Notification API which would be better but of course, Safari doesn't support it 💩

It's also missing the updating favicon with a badge, that's a bonus for another day :)

Let me know if you try this out.

**Comment by fwouts** [comment]
Closing as no longer planned.
