### ISSUE TITLE
Notification filtering

### ISSUE THREAD

**Issue by michaelpearce-at** [fwouts/prmonitor#772]
For the vast majority of cases, I am not interested in when the author has added a new commit. I'm interested when they tag me, request a review from me, or comment on a PR which I've been involved in. A large part of my interaction with PR Monitor seems to be "mute until next update from author" when they add a commit (it's especially annoying when it's just that they've merged the latest master into their branch).

A way to select which notifications I'm actually interested in would be nice. This includes the badge on the icon - it should only increase its count for notifications I've selected.

**Comment by fwouts** [comment]
Instead of implementing a whole new notifications preference screen, I opted to add a new muting option. Let me know what you think.
<img width="595" alt="Screen Shot 2020-06-05 at 8 40 52 am" src="https://user-images.githubusercontent.com/772570/83817512-51130780-a708-11ea-9cb9-052d01d5cd47.png">

**Comment by fwouts** [comment]
Giving it a bit more thought, this feature isn't quite what you need, because it only affects PRs that you have muted. It won't affect PRs that you have reviewed, and that automatically disappear from "Incoming PRs" because you have reviewed them. I guess we'll need these notification settings after all :)

**Comment by michaelpearce-at** [comment]
Ah, that latest commit should do nicely :)
